name: Scheduled API Tasks

on:
  schedule:
    # Run hourly
    - cron: '0 * * * *' # every hour
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  call-api-endpoints:
    runs-on: ubuntu-latest

    steps:
    - name: Call hourly task
      if: github.event.schedule == '0 * * * *'
      run: |
        curl -X POST https://aqi-forecasting-webapp-1.onrender.com/api/run_hourly_tasks

    - name: Call daily task
      if: github.event.schedule == '0 6 * * *'
      run: |
        curl -X POST https://aqi-forecasting-webapp-1.onrender.com/api/run_daily_tasks
